import React from 'react';
import './Contact.css';

const Contact = () => {
    return (
        <div>
            <div className='cTitle'>
                contact
            </div>
            <div className="contact">
                here is the contact page...
                here is the contact page...
                here is the contact page...
                here is the contact page...
                here is the contact page...
                here is the contact page...
                here is the contact page...
                here is the contact page...
                here is the contact page...
                here is the contact page...
                here is the contact page...
                here is the contact page...
                here is the contact page...
                here is the contact page...
                here is the contact page...
            </div>
        </div>
    )
}

export default Contact;